### ISSUE TITLE
Backwarts compatibilty to 1.8?

### ISSUE THREAD

**Issue by EvilOlaf** [Gamealition/GPrism#2]
I recently found this fork of Prism and gave it a shot.
Unfortunately it seems not to work decent on 1.8 as I got this error message in console when trying to use the `pr i` wand.

The database initialisation seemed to work well, no errors there.
Besides the MySQL credentials I did not change anything in the `config.yml` (yet).

```
[20:12:44 ERROR]: Could not pass event PlayerInteractEvent to Prism v1.11.2-2.0.10
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:763) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.getItemInMainHand()Lorg/bukkit/inventory/ItemStack;
        at me.botsko.prism.listeners.PrismPlayerEvents.onPlayerInteract(PrismPlayerEvents.java:348) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 18 more

``` 

Using obviously Paper on the for 1.8 recommended build and Gprism built from todays' source checkout.
`CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`

Thanks for taking a look into.

Olaf

**Comment by EvilOlaf** [comment]
When trying to run a `pr l` command with some arguments I get disconnected with the following message.
Client version is obviously 1.8.

![crash](https://cloud.githubusercontent.com/assets/3305006/23626423/27da179e-02ad-11e7-9700-b18a5a67d8ad.JPG)

**Comment by PhanaticD** [comment]
Just use the original prism then? minecraft is on 1.11.2

**Comment by RoyCurtis** [comment]
I appreciate the report. Sorry to say however, on this fork at least, I do not wish to maintain pre-1.11.2 compatibility.

I can't really suggest a workaround for the PlayerInteractEvent exception, but for the disconnect error try adding [cbarber's `-raw` flag](https://github.com/Gamealition/GPrism/pull/1). For example:

`/pr l r:5 -raw`

That should send the results as a plain message instead of JSON (which is what seems to be causing the kick).

**Comment by EvilOlaf** [comment]
I am aware that the current version of Minecraft is 1.11.2. However as you might probably know several servers are still on 1.8 for various reasons.
Also at least for me it was not absolutely clear that this would not work on versions below 1.11.

Anyway. As written I just wanted to give it a shot to see if it would run and may have some bugs fixed that I run into over the years.

Cheers
Olaf

**Comment by RoyCurtis** [comment]
Understood; that could be better documented. Sorry to disappoint again, but thanks for asking :)

**Comment by EvilOlaf** [comment]
No worries.
